{
 "title": "Urbanistica",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Stato dei parcheggi",
   "type": "table",
   "description": "Informazioni generali sullo stato dei parcheggi",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    sensor_name AS \"Parcheggio - Stallo\" , \n    CASE \n        WHEN is_available = TRUE THEN 'Non occupato'\n        WHEN is_available = FALSE THEN 'Occupato'\n    END AS \"DISPONIBILITÀ\",\n    CASE \n        WHEN plate = '' THEN 'Nessuna informazione sulla targa' \n        ELSE plate\n    END AS \"TARGA\",\n    gather_time AS \"LETTURA\", \n    CONCAT(ROUND(layoff / 60.0, 2), ' min') \n    AS \"PERMANENZA\"\nFROM \"sc_database\".\"parking\"\nWHERE (sensor_name, gather_time) IN (\n    SELECT sensor_name, MAX(gather_time)\n    FROM \"sc_database\".\"parking\"\n    GROUP BY sensor_name\n)\nORDER BY sensor_name ASC\n\n\n"
    }
   ]
  },
  {
   "title": "Miscellaneous pagamenti",
   "type": "bargauge",
   "description": "Informazioni generali sui pagamenti",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(bill) AS \"MEDIA PAGAMENTI\" FROM \"sc_database\".\"payment_parking\" GROUP BY sensor_name"
    },
    {
     "rawSql": "SELECT MAX(bill) AS \"PAGAMENTO PIÙ ALTO\" FROM \"sc_database\".\"payment_parking_mv\""
    },
    {
     "rawSql": "SELECT MIN(bill) AS \"PAGAMENTO PIÙ BASSO\" FROM \"sc_database\".\"payment_parking_mv\""
    }
   ]
  },
  {
   "title": "Pagamenti dei parcheggi ricevuti",
   "type": "logs",
   "description": "Lista dei pagamenti ricevuti dai parcheggi",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name, gather_time, bill AS \"Importo pagamento (€)\" FROM \"sc_database\".\"payment_parking\""
    }
   ]
  }
 ]
}