{
 "title": "Environmental Planning",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "temperature_sensor",
    "label": "Temperature sensor",
    "query": "SELECT sensor_name FROM sc_database.temperature"
   },
   {
    "name": "precipitation_intensity_sensor",
    "label": "Precipitation Intensity sensor",
    "query": "SELECT sensor_name FROM sc_database.precipitation_intensity"
   },
   {
    "name": "air_pollution_sensor",
    "label": "Air Pollution sensor",
    "query": "SELECT sensor_name FROM sc_database.air_pollution"
   }
  ]
 },
 "panels": [
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature in Padua, Italy",
   "type": "timeseries",
   "description": "Display of actual temperature in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, readings as Temperature, sensor_name FROM \"sc_database\".\"temperature\" WHERE ( time >= $__fromTime AND time <= $__toTime AND sensor_name IN (${temperature_sensor:singlequote})) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Heat Index in Padua, Italy",
   "type": "timeseries",
   "description": "Display of actual temperature vs heat index (apparent temperature).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expression": "(-8.78469475556)+((1.61139411)*${temp})+((2.338548839)*${hum})+((-0.146116050)*${temp}*${hum})+((-0.012308094)*(${temp}**2))+((-0.0164248277778)*(${hum}**2))+((0.002211732)*(${temp}**2)*${hum})+((0.00072546)*${temp}*(${hum}**2))+((-0.000003582)*(${temp}**2)*(${hum}**2))",
     "type": "math"
    }
   ]
  },
  {
   "title": "Humidity in Padua, Italy",
   "type": "timeseries",
   "description": "Display of humidity in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, readings as Humidity, sensor_name FROM \"sc_database\".\"humidity\" WHERE ( time >= $__fromTime AND time <= $__toTime AND sensor_name IN (${temperature_sensor:singlequote})) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Precipitation Intensity in Padua, Italy",
   "type": "timeseries",
   "description": "Display of precipitation intensity in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, readings as Precipitation, sensor_name FROM \"sc_database\".\"precipitation_intensity\" WHERE ( time >= $__fromTime AND time <= $__toTime AND sensor_name IN (${precipitation_intensity_sensor:singlequote})) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Air Pollution in Padua, Italy",
   "type": "timeseries",
   "description": "Display of air pollution in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, sensor_name, PM2_5, PM10, O3, NO2 FROM \"sc_database\".\"air_pollution\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND sensor_name IN (${air_pollution_sensor:singlequote}) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "PM 2.5 Level",
   "type": "timeseries",
   "description": "Display of PM 2.5 level in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, sensor_name, PM2_5 as \" \" FROM \"sc_database\".\"air_pollution\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND sensor_name IN (${air_pollution_sensor:singlequote}) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "PM 10 Levels in Padua",
   "type": "timeseries",
   "description": "Display of PM 20 level in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, sensor_name, PM10 as \" \" FROM \"sc_database\".\"air_pollution\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND sensor_name IN (${air_pollution_sensor:singlequote}) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "O3 Level in Padua",
   "type": "timeseries",
   "description": "Display of O3 level in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, sensor_name, O3 as \" \" FROM \"sc_database\".\"air_pollution\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND sensor_name IN (${air_pollution_sensor:singlequote}) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "NO2 Level in Padua",
   "type": "timeseries",
   "description": "Display of NO2 level in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, sensor_name, NO2 as \" \" FROM \"sc_database\".\"air_pollution\" WHERE ( time >= $__fromTime AND time <= $__toTime ) AND sensor_name IN (${air_pollution_sensor:singlequote}) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Water Level in Padua, Italy",
   "type": "timeseries",
   "description": "Display of water level in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT gather_time as time, readings as Water, sensor_name FROM \"sc_database\".\"water_level\" WHERE ( time >= $__fromTime AND time <= $__toTime AND sensor_name IN (${precipitation_intensity_sensor:singlequote})) ORDER BY time ASC"
    }
   ]
  },
  { "title": "Means", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Average Temperature in Padua, Italy",
   "type": "gauge",
   "description": "Display of average temperature in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(t1.readings)\r\nFROM \r\n(SELECT readings from temperature\r\nWHERE (gather_time >= $__fromTime AND gather_time <= $__toTime)\r\nAND gather_time in (select max(gather_time) from temperature group by sensor_name)) t1"
    }
   ]
  },
  {
   "title": "Average Heat Index in Padua, Italy",
   "type": "gauge",
   "description": "Display of average apparent temperature in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(-8.78469475556)+((1.61139411)*${temp})+((2.338548839)*${hum})+((-0.146116050)*${temp}*${hum})+((-0.012308094)*(${temp}**2))+((-0.0164248277778)*(${hum}**2))+((0.002211732)*(${temp}**2)*${hum})+((0.00072546)*${temp}*(${hum}**2))+((-0.000003582)*(${temp}**2)*(${hum}**2))",
     "type": "math"
    }
   ]
  },
  {
   "title": "Average Humidity in Padua, Italy",
   "type": "gauge",
   "description": "Display of average humidity in Padua.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(h1.readings)\r\nFROM \r\n(SELECT readings from humidity\r\nWHERE (gather_time >= $__fromTime AND gather_time <= $__toTime)\r\nAND gather_time in (select max(gather_time) from humidity group by sensor_name)) h1"
    }
   ]
  },
  {
   "title": "Average Precipitation Intensity in Padua, Italy",
   "type": "gauge",
   "description": "Displays of average precipitations on Padua.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(pi1.readings)\r\nFROM \r\n(SELECT readings from precipitation_intensity\r\nWHERE (gather_time >= $__fromTime AND gather_time <= $__toTime)\r\nAND gather_time in (select max(gather_time) from precipitation_intensity group by sensor_name)) pi1"
    }
   ]
  },
  {
   "title": "Average Water Level in Padua, Italy",
   "type": "gauge",
   "description": "Displays of average water level on Padua.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(wl1.readings)\r\nFROM \r\n(SELECT readings from water_level\r\nWHERE (gather_time >= $__fromTime AND gather_time <= $__toTime)\r\nAND gather_time in (select max(gather_time) from water_level group by sensor_name)) wl1"
    }
   ]
  },
  {
   "title": "Average PM 2,5 Concentration in Padua, Italy",
   "type": "gauge",
   "description": "Displays the average concentration of pm 2,5 particles suspended in air in Padua.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(ap1.PM2_5) FROM (SELECT PM2_5 FROM air_pollution WHERE (gather_time >=$__fromTime AND gather_time <= $__toTime) AND gather_time IN (SELECT max(gather_time) FROM air_pollution group by sensor_name)) ap1"
    }
   ]
  },
  {
   "title": "Average PM 10 Concentration in Padua, Italy",
   "type": "gauge",
   "description": "Displays the average concentration of pm 10 particles suspended in air in Padua.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(ap1.PM10) FROM (SELECT PM10 FROM air_pollution WHERE (gather_time >=$__fromTime AND gather_time <= $__toTime) AND gather_time IN (SELECT max(gather_time) FROM air_pollution group by sensor_name)) ap1"
    }
   ]
  },
  {
   "title": "Average 03 Concentration in Padua, Italy",
   "type": "gauge",
   "description": "Displays the average concentration of O3 in the air in Padua.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(ap1.O3) FROM (SELECT O3 FROM air_pollution WHERE (gather_time >=$__fromTime AND gather_time <= $__toTime) AND gather_time IN (SELECT max(gather_time) FROM air_pollution group by sensor_name)) ap1"
    }
   ]
  },
  {
   "title": "Displays the average concentration of NO2 particles suspended in air in Padua.",
   "type": "gauge",
   "description": "Displays the average concentration of pm NO2 suspended in air in Padua.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(ap1.NO2) FROM \r\n(SELECT NO2 FROM air_pollution WHERE \r\n(gather_time >=$__fromTime AND gather_time <= $__toTime) AND gather_time IN (SELECT max(gather_time) FROM air_pollution group by sensor_name)) ap1"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Heat Index Statistics in Padua, Italy",
   "type": "barchart",
   "description": "Display of statistics about apparent temperature in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT h1.sensor_name as Sensor, AVG(h1.heat_index) as \"Average\", MAX(h1.heat_index) as \"Max\", MIN(h1.heat_index) as \"Min\"\r\nFROM\r\n(SELECT t.sensor_name, t.readings as temp, h.readings as hum, t.gather_time as time,\r\n(-8.78469475556)+((1.61139411)*temp)+((2.338548839)*hum)+((-0.146116050)*temp*hum)+((-0.012308094)*(POWER(temp,2)))+((-0.0164248277778)*(POWER(hum,2)))+((0.002211732)*(POWER(temp,2))*hum)+((0.00072546)*temp*(POWER(hum,2)))+((-0.000003582)*(POWER(temp,2))*(POWER(hum,2))) as heat_index\r\nFROM sc_database.temperature t\r\nJOIN sc_database.humidity h\r\nON h.sensor_name = t.sensor_name AND h.gather_time = t.gather_time) h1\r\nWHERE ( time >= $__fromTime AND time <= $__toTime )\r\nGROUP by h1.sensor_name"
    }
   ]
  },
  {
   "title": "Temperature Statistics in Padua, Italy",
   "type": "barchart",
   "description": "Display of statistics about actual temperature in Padua.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT t6.sensor_name as Sensor, a as Average, mean as Mean, m as \"Min\", mx as \"Max\"\r\nFROM\r\n(SELECT t4.sensor_name, AVG(t4.readings) as mean\r\nFROM \r\n(SELECT t2.sensor_name, t3.readings, t3.c\r\nFROM\r\n(SELECT t1.sensor_name, MAX(t1.c) as c from \r\n(SELECT t.sensor_name, t.readings, COUNT(t.sensor_name) as c from (select sensor_name, readings, gather_time as time from temperature WHERE ( time >= $__fromTime AND time <= $__toTime ) ORDER BY time desc) t group by t.sensor_name, t.readings) t1\r\ngroup by sensor_name ) t2\r\nLEFT JOIN\r\n(SELECT t.sensor_name, t.readings, COUNT(t.sensor_name) as c from (select sensor_name, readings, gather_time as time from temperature WHERE ( time >= $__fromTime AND time <= $__toTime ) ORDER BY time desc) t group by t.sensor_name, t.readings) t3\r\nON t2.sensor_name = t3.sensor_name AND t3.c = t2.c ) t4\r\ngroup by t4.sensor_name) t5\r\nLEFT JOIN\r\n(SELECT t.sensor_name, AVG(t.readings) as a, MIN(readings) as m, MAX(readings) as mx FROM (select sensor_name, readings, gather_time as time from temperature WHERE ( time >= $__fromTime AND time <= $__toTime ) ORDER BY time desc) t group by t.sensor_name) t6\r\nON t5.sensor_name = t6.sensor_name\r\n\r\n"
    }
   ]
  }
 ]
}