{
 "title": "Urban planning",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "State of the parking lots",
   "type": "table",
   "description": "General information on the status of car parks",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    sensor_name AS \"Parking - Spot\" , \n    CASE \n        WHEN is_available = TRUE THEN 'Unoccupied'\n        WHEN is_available = FALSE THEN 'Occupied'\n    END AS \"AVAILABILITY\",\n    CASE \n        WHEN plate = '' THEN 'No information on the license plate' \n        ELSE plate\n    END AS \"PLATE\",\n    DATE_FORMAT(gather_time, '%d %b %Y, %H:%i:%s') AS \"READING\", \n    CONCAT(ROUND(layoff / 60.0, 2), ' min') \n    AS \"DURATION\"\nFROM \"sc_database\".\"parking\"\nWHERE (sensor_name, gather_time) IN (\n    SELECT sensor_name, MAX(gather_time)\n    FROM \"sc_database\".\"parking\"\n    GROUP BY sensor_name\n)\nORDER BY sensor_name ASC\n\n\n"
    }
   ]
  },
  {
   "title": "Payment miscellaneous",
   "type": "bargauge",
   "description": "General payment information",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(bill) AS \"AVERAGE PAYMENT\" FROM \"sc_database\".\"payment_parking\""
    },
    {
     "rawSql": "SELECT MAX(bill) AS \"HIGHEST PAYMENT\" FROM \"sc_database\".\"payment_parking_mv\""
    },
    {
     "rawSql": "SELECT MIN(bill) AS \"LOWEST PAYMENT\" FROM \"sc_database\".\"payment_parking_mv\""
    }
   ]
  },
  {
   "title": "Parking payments received",
   "type": "logs",
   "description": "List of payments received from car parks",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name, gather_time, bill AS \"Payment amount (€)\" FROM \"sc_database\".\"payment_parking\""
    }
   ]
  }
 ]
}