apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: sc_database
      port: 9000
      host: clickhouse
      username: sc_admin
      # disable check cert
      tlsSkipVerify: false
    secureJsonData:
      password: sc_password
    isDefault: true
