name: release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  releases:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: create release with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pushd "${GITHUB_WORKSPACE}" 
          zip -r "${GITHUB_REF_NAME}_PoC.zip" .
          popd
          mv "${GITHUB_WORKSPACE}/${GITHUB_REF_NAME}_PoC.zip" .
          gh release create "$GITHUB_REF_NAME" -t "$GITHUB_REF_NAME" "${GITHUB_REF_NAME}_PoC.zip" -n "Proof of Concept relativo alla milestone **${GITHUB_REF_NAME}**." 
        env:
          GITHUB_TOKEN: ${{ github.token }}
